[package]
name = "subsetter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
indicatif ={ version = "0.17.8" }
rayon = { version = "1.10.0" }
ttf-parser = "0.25.0"
