[package]
name = "subsetter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
hb-subset = { version = "0.3.0", features = ["bundled"] }
indicatif ={ version = "0.17.8" }
rayon = { version = "1.10.0" }
ttf-parser = "0.25.0"
woff = "0.3.3"
